project:
  type: book
  output-dir: docs

book:
  title: "DS2023 Catapult Group 2 Final Project"
  author: "Alka Link, Grace Pitts, Kieran Perdue, Michael Carlson"
  favicon: logo.png
  description: "Preventing Fatigue and Injury in Collegiate Basketball"
  keyword: data science, communicating, storytelling, data visualization, data design
  url: https://mrcarlson3.github.io/DS2023Proj/
  sidebar: 
    logo: logo.png
    search: true
  repo-url: https://github.com/mrcarlson3/DS2023Proj
  repo-branch: main
  image: logo.png

  chapters:
    - index.qmd
    - datalearning.qmd
    - eda.qmd
    - dataviz.qmd
    - datadictionary.qmd



format:
  html:
    theme:
      light: united
    code-fold: false
    backgroundcolor: '#FFFFFF'



